# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 1800

  # Point to the official Kali Linux box
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2025.1.0"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.memory = "4096"
    vb.cpus = "2"
    vb.name = "CyberLabVM-Kali"
  end

  config.vm.synced_folder "./code", "/home/vagrant/Desktop/cyber-lab"
  config.vm.provision "shell", path: "bootstrap.sh"
end